### ISSUE TITLE
`ignore` 옵션 사용에 대한 질문

### ISSUE THREAD

**Issue by kizmo04** [toss/yarn-plugin-workspace-since#14]
안녕하세요, 먼저 유용한 플러그인을 오픈소스로 공개해 주셔서 감사합니다. 😄 

yarn workspace since 를 ignore 옵션과 같이 사용하면서 이슈가 있었는데요,
의도된 결과인지 추측이 어려워서 질문 겸 제보를 드립니다. 

## 재현방법
프로젝트 구조는 다음과 같으며, `sdk`, `model` 에 모두 변경사항이 있는 상황입니다.
```shell
.
├── package.json
├── packages
│   ├── sdk
│   ├── model
...
```

프로젝트 루트의 `workspaces` 필드에 'packages/*' 처럼 globpattern을 사용해서 지정한 상태입니다.

`<root>/package.json`
```json
{
  workspaces: ['packages/*']
}
```

이후, `yarn workspaces since run --ignore '*/model' 'start' $(git rev-parse HEAD~2)`를 실행하면,
<img width="489" alt="스크린샷 2022-07-28 14 54 16" src="https://user-images.githubusercontent.com/23042971/181430827-8e99eb3f-831f-4cf8-a6e2-20e11b567f39.png">
모든 패키지에 대해서 커맨드가 실행됩니다.

## 기대한 반응
`ignore` 옵션으로 준 `*/model` 패턴과 매치되는 `model` 패키지는 커맨드가 실행되지 않는 것을 기대했었는데요, 실행 결과는 `ignore` 되지 않습니다.

## 제안

```
{
  workspaces: ["packages/*"]
}
```
처럼 workspaces 필드에 배열로 glob pattern을 사용해서 지정된 경우, 
matchedWorkspaceGlobs 를 필터링 할 때 'packages/*' 와 비교하게 되어서 필터링이 되지 않는 것 같습니다..!

현재는 ignore 옵션을 이용하려면,

```json
{
  workspaces: ["packages/sdk", "packages/model"]
}
```
이렇게 지정해야 할 것 같은데요, 혹시 다른 방법이 있을까요..? 
아니라면 `['packages/*']` 처럼 지정되었을 때도 비교가 가능하면 좋을 것 같아서 제안드려봅니다..!

**Comment by raon0211** [comment]
말씀하신 부분을 살펴보면 버그인 것 같네요. 내부에서 살펴보도록 하겠습니다.

**Comment by raon0211** [comment]
#17 에서 해결되었습니다. 감사합니다!
